on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: Build and deploy wasm R package repository

jobs:
  deploy-cran-repo:
    uses: r-wasm/actions/.github/workflows/deploy-cran-repo.yml@v2
    with:
      webr-image: "ghcr.io/r-wasm/webr:v0.4.0"
    permissions:
      repository-projects: read
      pages: write
      id-token: write
